export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT'
export const GET_ACCOUNT = 'GET_ACCOUNT'
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR'
export const SET_LOADING = 'SET_LOADING'

export const REMOVE_IMAGE = 'REMOVE_IMAGE' 
export const ADD_IMAGE = 'ADD_IMAGE'
export const IMAGE_LOADING = 'IMAGE_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const REMOVE_ALL = 'REMOVE_ALL'

export const CLEAR_POST = 'CLEAR_POST'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const PREDICT_LOADING = 'PREDICT_LOADING'
export const PREDICT_ERROR = 'PREDICT_ERROR'
export const UPDATE_SCORE = 'UPDATE_SCORE' 